zombie:
  health: 40.0          # ค่าพลังชีวิตสูงสุดของซอมบี้
  speed: 1            # ความเร็วการเคลื่อนที่ของซอมบี้
  jump_interval: 60     # ระยะเวลาการกระโดด (หน่วย: ticks, 20 ticks = 1 วินาที)
  jump_height: 1     # ความสูงในการกระโดดของซอมบี้
  damage: 5.0         # ความเสียหายที่ซอมบี้สามารถทำได้
